using Microsoft.Win32;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

namespace Biscuit.winform {
	public static class gMisc {

		public static string? GetAppPath() {	// auto generated by copilot
			return System.IO.Path.GetDirectoryName(System.Reflection.Assembly.GetExecutingAssembly().Location);
		}

		public static bool LoadWindowPos(RegistryKey reg, Form form) {
			if (form is null)
				return false;
			string? str = reg.GetValue("Rect", "") as string;
			string[]? strs = str?.Split(',');
            if (strs is not null && strs.Length >= 4) {
				var l = Biscuit.misc.StrTo(strs[0], form.Left);
				var t = Biscuit.misc.StrTo(strs[1], form.Top);
				var w = Biscuit.misc.StrTo(strs[2], form.Width);
				var h = Biscuit.misc.StrTo(strs[3], form.Height);
				bool bFitInScreen = false;
				foreach (var screen in Screen.AllScreens) {
					var wa = screen.WorkingArea;
					// check if the LeftTop corner is in the screen with some margin
					if (l + 10 >= wa.Left && l + 100 <= wa.Right && t + 10 >= wa.Top && t + 100 <= wa.Bottom) {
						bFitInScreen = true;
						break;
					}
				}
				if (bFitInScreen) {
					form.Left = l;
					form.Top = t;
					form.Width = w;
					form.Height = h;
				}
			}

			bool bMaximized = (int)reg.GetValue("Maximized", 0) != 0;
			form.WindowState = bMaximized ? FormWindowState.Maximized : FormWindowState.Normal;

			return true;
		}

		public static bool SaveWindowPos(RegistryKey reg, Form form) {
			if (form is null)
				return false;
			bool bMaximized = (form.WindowState == FormWindowState.Maximized);
			reg.SetValue("Maximized", bMaximized ? 1 : 0);
			if (!bMaximized) {
				string str = $"{form.Left},{form.Top},{form.Width},{form.Height}";
				reg.SetValue("Rect", str);
			}
			return true;
		}
	}
}
